-- Users table storing the users who has access to the application
DROP TABLE IF EXISTS users_roles;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS contacts;

CREATE TABLE users
(
    user_id  int GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
    username varchar(255)                         NOT NULL,
    password varchar(255)                         NOT NULL,
    enabled  boolean DEFAULT NULL,
    PRIMARY KEY (user_id)
);

-- Roles table
CREATE TABLE roles
(
    role_id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL,
    name    varchar(255) NOT NULL,
    PRIMARY KEY (role_id)
);

-- User to Roles mapping
CREATE TABLE users_roles
(
    user_id int NOT NULL,
    role_id int NOT NULL
);
ALTER TABLE users_roles ADD CONSTRAINT user_fk FOREIGN KEY (user_id) REFERENCES users(user_id);
ALTER TABLE users_roles ADD CONSTRAINT role_fk FOREIGN KEY (role_id) REFERENCES roles(role_id);

-- Contact Table for storing the contacts
CREATE TABLE contacts
(
    id         int GENERATED BY DEFAULT AS IDENTITY(START WITH 1000, INCREMENT BY 1) NOT NULL,
    first_name varchar(255) DEFAULT NULL,
    last_name  varchar(255) DEFAULT NULL,
    email      varchar(255) DEFAULT NULL,
    PRIMARY KEY (id)
);
